apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
  namespace: proxy-test
spec:  
  selector:
    matchLabels:
      app: poc
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: poc
    spec:
      serviceAccount: proxy-root-runner
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
      - name: certs
        configMap:
          name: certs
      initContainers:
      - image: wistefan/sidecar-init
        name: init
        imagePullPolicy: Always
        securityContext:
          privileged: true
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echo
        securityContext:
          privileged: true
      - image: wistefan/go-auth
        name: auth
        env:
          - name: SERVER_PORT
            value: "7070"
          - name: IDP_URL
            value: "http://idp-happypets-shop.i4trust-dev.fiware.io/oauth2/token"
        volumeMounts:
        - name: certs
          mountPath: /go/src/app/certs/
      - image: envoyproxy/envoy:v1.20.0
        name: envoy
        args: ["-l trace", "-c /etc/envoy/envoy.yaml"]
        securityContext:
          runAsUser: 1337
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: additional
  namespace: proxy-test
spec:
  selector:
    matchLabels:
      app: additional
  replicas: 1
  template:
    metadata:
      labels:
        app: additional
    spec:
      serviceAccount: proxy-root-runner
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echo-add
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: additional-service
  labels:
    app: additional
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  selector:
    app: additional
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: proxy-test
data:
  listener.yaml: |
    resources:
      - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
        name: envoy_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 15001
        traffic_direction: OUTBOUND
        listener_filters:
        - name: envoy.filters.listener.tls_inspector
        - name: envoy.filters.listener.original_dst  
        filter_chains:
        - name: https_chain
          filter_chain_match: 
            transport_protocol: tls
          filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              cluster: passthrough-https
              stat_prefix: https_passthrough
        - name: http_chain
          filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                - name: allow_any
                  domains:
                  - "*"
                  routes:
                  - match: 
                      prefix: "/"
                    route: 
                      cluster: passthrough
                    typed_per_filter_config:
                      envoy.filters.http.lua:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                        disabled: true
                - name: local_service
                  domains:
                  - "additional-service"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: additional-service
              http_filters:
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  inline_code: |
                    function envoy_on_request(request_handle)
                      local domain = request_handle:headers():get(":authority")                      
                      local path = request_handle:headers():get(":path")

                      local headers, body = request_handle:httpCall(
                      "ext-authz",
                      {
                        [":method"] = "GET",
                        [":path"] = "/token?domain=" .. domain .. "&path=" .. path,
                        [":authority"] = "ext-authz"
                      },
                      null,
                      5000)
                      request_handle:headers():add("Authorization", body)
                    end
              - name: envoy.filters.http.router
  cluster.yaml: |
    resources:
      - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        name: passthrough
        type: ORIGINAL_DST
        connectTimeout: 10s
        lbPolicy: CLUSTER_PROVIDED
        original_dst_lb_config:
          use_http_header: true
      - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        name: passthrough-https
        type: ORIGINAL_DST
        connectTimeout: 10s
        lbPolicy: CLUSTER_PROVIDED
      - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        name: ext-authz
        type: STRICT_DNS
        connect_timeout: 1s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: additional-service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 7070
      - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        name: additional-service
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: additional-service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: "additional-service"
                    port_value: 80
      - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        name: additional-service-tls
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: additional-service-tls
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: "additional-service"
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls  
          typed_config:  
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
  envoy.yaml: |
    node:
      cluster: passthrough
      id: envoy-node
    dynamic_resources:
      cds_config:
        path: /etc/envoy/cluster.yaml
      lds_config:
        path: /etc/envoy/listener.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certs
  namespace: proxy-test
data:
  token.pem: |
    <insert key>
  token.cer: |
    <insert certificate>