resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: passthrough
    type: ORIGINAL_DST
    connectTimeout: 10s
    lbPolicy: CLUSTER_PROVIDED
    original_dst_lb_config:
      use_http_header: true
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: passthrough-https
    type: ORIGINAL_DST
    connectTimeout: 10s
    lbPolicy: CLUSTER_PROVIDED
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: ext-authz
    type: STRICT_DNS
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: ext-authz
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                protocol: TCP
                address: 0.0.0.0
                port_value: 7070