micronaut:
  application:
    name: ${project.artifactId}

  server:
    port: 8080

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

---
endpoints:
  metrics:
    enabled: true
  health:
    enabled: true

loggers:
  levels:
    ROOT: TRACE
    io:
      micronaut:
        http:
          client: TRACE
---

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

---
general:
  updateDelayInS: 2

# configuration when running inside openshift service mesh
---
meshExtension:
  enabled: true
  authProviderName: outbound|80||ext-authz
  workloadSelector:
    name: app
    value: app
  filterVersion: ${project.version}
  extensionName: cached-auth-filter-extension
  extensionNamespace: extension-namespace
  meshExtensionYamlPath: ./service-mesh-extension.yaml
  annotations:
    - name: annotation
      value: annotation-value
  labels:
    - name: label
      value: label-value

# Configuration when running with plain envoy
---
envoy:
  enabled: true
  externalAuth:
    address: auth-service
    port: 7070
  socketAddress:
    address: 0.0.0.0
    port: 15001
  listenerYamlPath: ./listener.yaml
  clusterYamlPath: ./cluster.yaml
  wasmFilterPath: /cached-auth-filter/cached-auth-filter.wasm