micronaut:
  application:
    name: ${project.artifactId}

  server:
    port: 8080

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

---
endpoints:
  metrics:
    enabled: true
  health:
    enabled: true

loggers:
  levels:
    ROOT: TRACE
    io:
      micronaut:
        http:
          client: TRACE
---

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

---

proxy:
  externalAuth:
    address: auth-service
    port: 7070
  socketAddress:
    address: 0.0.0.0
    port: 15001
  listenerYamlPath: ./listener.yaml
  clusterYamlPath: ./cluster.yaml
  updateDelayInS: 2
  wasmFilterPath: /cached-auth-filter/cached-auth-filter.wasm