apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ext-authz
spec:
  hosts:
  - ext-authz
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: ecs-ishare-endpoint-auth-service
    ports:
      http: 8080