name: Endpoint-Config-Service

on:
  push

jobs:

  endpoint-service-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '17'
        java-package: jdk

    - name: Run tests
      run: |
        cd src/endpoint-configuration-service/
        mvn clean test

  endpoint-service-deploy:

    needs: endpoint-service-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '17'
        java-package: jdk

    - name: Log into quay.io
      run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

    - name: Build&Push image
      run: |
        cd src/endpoint-configuration-service/
        mvn versions:set -DnewVersion=latest
        mvn clean install deploy -DskipTests -Dimage.tag=latest -Dimage.registry="quay.io/"