name: iShare-Auth-Provider

on:
  push

jobs:

  ishare-auth-provider-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17.3

      - name: Go test
        run: |
          cd src/ishare-auth-provider/
          go test

  ishare-auth-provider:

    needs: ishare-auth-provider-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ishare-auth-provider
          tags: latest ${{ github.sha }}
          dockerfiles: |
            ./src/ishare-auth-provider/Dockerfile
          context: ./src/ishare-auth-provider

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/wi_stefan
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}