name: Unit-Test

on:
  push

jobs:

  endpoint-service-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '17'
        java-package: jdk

    - name: Run tests
      run: |
        cd src/endpoint-configuration-service/
        mvn clean verify

    - name: Upload coverage-report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco.exec
        path: src/endpoint-configuration-service/target/site/jacoco/test.exec

  ishare-auth-provider-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.3

    - name: Go test
      run: |
        cd src/ishare-auth-provider/
        go test -v -covermode=count -coverprofile=coverage.out

    - name: Upload coverage-report
      uses: actions/upload-artifact@v2
      with:
        name: auth-provider.info
        path: src/ishare-auth-provider/coverage.out